language: java
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarqube.com
  -Dsonar.organization=lujjlujj-github -Dsonar.login=$SONAR_QUBE_TOKEN
notifications:
  email: false
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: lujunjie400428@126.com
  password: $PCF_PASSWORD
  organization: terrylu.org
  space: development
  on:
    repo: lujjlujj/ebuy